# Change these first
owner: KaratekHD # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Homepage
    url: https://karatek.net
  - name: IServ
    url: $SECRET_SITE
    icon: https://iserv.de/user/sites/iserv/themes/iserv/images/favicon.ico
  - name: IServ L
    url: $LEHRTE
    icon: https://iserv.de/user/sites/iserv/themes/iserv/images/favicon.ico
  - name: IServ S
    url: $SEHNDE
    icon: https://iserv.de/user/sites/iserv/themes/iserv/images/favicon.ico
  - name: openSUSE Meet
    url: https://meet.opensuse.org
    icon: https://static.opensuse.org/favicon.svg
#  - name: IServ ViKo bbbha60b2
#    url: https://bbbha60b2.videoconference.iserv.eu
#    icon: https://iserv.de/user/sites/iserv/themes/iserv/images/favicon.ico


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: karatekhd.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://karatek.net/img/logo.png
  name: Karatek Monitor
  introTitle: "This is the **Karatek Monitor**."
  favicon: https://karatek.net/img/logo.png
  introMessage: It shows the uptime of some **external** services I'd like to monitor. If you want me to add something here, feel free to drop me a line, see my [contact page](https://karatek.net/Legal/contact/)
  navbar:
    - title: Monitor
      href: /
    - title: Homepage
      href: https://karatek.net
    - title: Blog
      href: https://blog.karatek.net


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration .
